### ISSUE TITLE
User unable to edit the first class in the schedule hours

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#495] opened 2018-12-19 11:29 UTC
Go to any user
click on the schedule hours
Try to edit the first hour "קבלת תלמידים"
Error console below

Try to replace to any other Lesson

main.164a4a0059cf4547723f.js:1 ERROR TypeError: Cannot read property 'class' of undefined
    at main.164a4a0059cf4547723f.js:1
    at e.object.r [as _next] (main.164a4a0059cf4547723f.js:1)
    at e.__tryOrUnsub (main.164a4a0059cf4547723f.js:1)
    at e.next (main.164a4a0059cf4547723f.js:1)
    at e._next (main.164a4a0059cf4547723f.js:1)
    at e.next (main.164a4a0059cf4547723f.js:1)
    at e.next (main.164a4a0059cf4547723f.js:1)
    at e.emit (main.164a4a0059cf4547723f.js:1)
    at Object.handleEvent (main.164a4a0059cf4547723f.js:1)
    at Object.handleEvent (main.164a4a0059cf4547723f.js:1)

**Comment by mr372e** [comment] 2018-12-23 08:43
Could not reproduce. This was probebly fixed in another issue.

**Closed by mr372e** 2018-12-23 08:43 UTC
Labels: in progress
