### ISSUE TITLE
Web portal - Maps - Added map not exist

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#572] opened 2019-01-03 06:45 UTC
Maps - Added map not exist (not displayed). Scenario: Press "Add map", define name and upload picture. In F12 see response 201 Created.  New map does not appears in map list. Note: I do not request for GET added map

**Comment by lanalazar** [comment] 2019-01-03 07:09
Exist bug 554

**Comment by KfirMor** [comment] 2019-02-10 15:16
Duplicate of #554

**Closed by KfirMor** 2019-02-10 15:16 UTC
Labels: bug
