### ISSUE TITLE
Web portal - after add new student Google pop-up "Save password" appears

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#569] opened 2019-01-03 04:43 UTC
After add new student Google pop-up "Save password" appears. According to Leora Perry:	אין להציג את מסך שמירת ססמא של גוגל לאחר יצירת תלמיד

**Comment by eran1205** [comment] 2019-01-03 04:51
If someone will get to this bug, please look at https://stackoverflow.com/questions/32369/disable-browser-save-password-functionality/37292424#37292424

**Comment by lanalazar** [comment] 2019-01-03 05:02
Sorry, bug 178 is opened

**Comment by KfirMor** [comment] 2019-02-10 15:16
Duplicate of #178

**Closed by KfirMor** 2019-02-10 15:16 UTC
Labels: bug
