### ISSUE TITLE
Web - Maps - impossible to edit maps navigation or maps blocked area

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#662] opened 2019-02-04 06:08 UTC
Principle define any maps navigation area or maps blocked area. Open this area (select from list and click). Try to edit it - get message that this area just exist. Is it correct??

**Comment by lanalazar** [comment] 2019-02-04 06:08
![Cannot edit navigation or blocked area.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfbafaa18b7ec0011210913/125516c66e82c728ace21e0d46cb95942d8d97e98aedb657e453f18220412667200bad6b7f97a32ab34d780a0a0b5efd030d0e56e0ebc969f9ec6923ce4e01ffd43f5f71923840a5ea831fee09be208b4ed7b5ef8b4b93ba2f39f5c9de116a415841c3aa1f27aa8b4ac152f74ee54457a2133362e37e367a55d9.JPG)

**Comment by eran1205** [comment] 2019-02-13 09:08
@lanalazar Hi Sveta, I couldn't reproduce this bug right now. Can you try?

**Comment by michalheim32** [comment] 2019-02-17 08:08
@eran1205  this was fixed by Yossi

**Closed** 2019-02-17 08:21 UTC
Labels: bug, review
