### ISSUE TITLE
Web portal - No toast message when student creation file is successfully upload

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#502] opened 2018-12-20 08:38 UTC
Principle upload file to add new students. According to US #74, If file is valid, add the new students to the students list. Show a toast message: קובץ נטען בהצלחה Actially, there is no toast message

**Comment by mr372e** [comment] 2018-12-23 11:01
Could not reproduce. Toast message was shown correctly for a valid file and empty file. This was probably closed by another pull request.

**Closed by mr372e** 2018-12-23 11:01 UTC
Labels: in progress
